### ISSUE TITLE
Unify and apply a local run scenario for the default of sbt run

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi#2]
The main purpose of this combined sbt file is the easy start of the complete Delphi application for developers or evaluators. Expecting a running instance of elasticsearch the `run` task starts the crawler, the webapi, the webapp, and the management application). 
Currently, these four instances are not configured to expect each other on their default ports, etc. 

Thus, in this task, please:
- Harmonize and document default ports so that the component can run alongside each other.
- Adjust project configurations to link these systems together by default. (For this also have a look at delphi-hub/delphi-management#14)

**Comment by janniclas** [comment]
Just a quick udpate;
the delphi-management commit linked in the submodule of this repository does not yet contain the current version of delphi-management. 
In fact the linked delphi-management repository is empty. 
Therefore, we are currently working on the sbt file to support the current development branches of all projects, because these actually contain an actual and current version of the components. 
Currently, there are some dependency issues when integrating delphi-management on which we are still working.

**Comment by janniclas** [comment]
I figured out how to resolve the dependency issues and changed the default ports in the projects build.sbt files. 
Therefore, I have updated all necessary dependencies and the used sbt version in all projects to 1.1.1 to match the version used in this repository.
I would like to propose to create a develop branch in this repository, whose git submodules point to the develop version of the other components. To this brach I would like to add the necessary changes I made to the config files of this repository. This would enable us to actually use the newly created sbt run all file to execute the current develop version of the program not only the master branch (which as mentioned above, currently doesn't contain any actual code).
@bhermann if you agree, can you please create the develop branch so I am able to create a pull request containing my changes.

**Comment by bhermann** [comment]
@janniclas Agreed... Branches have been created, protected, and proper permissions have been set.

**Comment by janniclas** [comment]
regarding the project configuration for linking the projects together I plan to wait for the results from https://github.com/delphi-hub/delphi-management/issues/14 to make sure I work on the most current version of the modules. 
@bhermann, if there is something to do on the current version I am currently missing I would ask you to clarify the linking process you were referring to in the issue. 
Else I would ask you @24santoshr,  @anitha181992 to notify me once you are finished so I can continue the work from there.

**Comment by bhermann** [comment]
@janniclas Until the completion of delphi-hub/delphi-management#14 there is nothing more to do I believe.

**Comment by bhermann** [comment]
Closed as discussed
