### ISSUE TITLE
Add ScalaStyle to all components

### ISSUE THREAD

**Issue by bhermann** [delphi-hub/delphi#4]
**Is your feature request related to a problem? Please describe.**
Not directly. Just code quality in general.

**Describe the solution you'd like**
I'd like to see ScalaStyle ( https://github.com/scalastyle/scalastyle ) to be run with the tests of each component. Maybe component specific configuration files are necessary.. maybe not.  

**Describe alternatives you've considered**
None... Is there something else like that?

**Additional context**
Not applicable

**Comment by bhermann** [comment]
Also have a look at scalariform (https://github.com/scala-ide/scalariform) please.

**Comment by bhermann** [comment]
Copy and adapt the configuration from delphi-management into all other projects. 
See delphi-hub/delphi-management#29

**Comment by hariharansrc** [comment]
Feature/4/scalastyle
